--Create tables
CREATE TABLE dbo.Buyers
(
	BuyerID	INT IDENTITY (1,1)	NOT NULL,
	Name NVARCHAR(100) NOT NULL,

	CONSTRAINT [PK_dbo.Buyers] PRIMARY KEY CLUSTERED (BuyerID ASC)
);

CREATE TABLE dbo.Sellers
(
	SellerID	INT IDENTITY (1,1)	NOT NULL,
	Name NVARCHAR(100) NOT NULL,

	CONSTRAINT [PK_dbo.Sellers] PRIMARY KEY CLUSTERED (SellerID ASC)
);


CREATE TABLE dbo.Items
(
	ItemID	INT IDENTITY (1,1)	NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(400) NOT NULL,
	SellerID INT NOT NULL,

	CONSTRAINT [PK_dbo.Items] PRIMARY KEY CLUSTERED (ItemID ASC),
	CONSTRAINT [FK_dbo.Items] FOREIGN KEY (SellerID) REFERENCES Sellers(SellerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE dbo.Bids
(
	BidID	INT IDENTITY (1,1)	NOT NULL,
	ItemID	INT NOT NULL,
	BuyerID INT NOT NULL,
	Price INT NOT NULL,
	Timestamp DATETIME NOT NULL,

	CONSTRAINT [PK_dbo.Bids] PRIMARY KEY CLUSTERED (BidID ASC),
	CONSTRAINT [FK1_dbo.Bids] FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT [FK2_dbo.Bids] FOREIGN KEY (BuyerID) REFERENCES Buyers(BuyerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);



